ok-up

diff --git a/lib-prj b/lib-prj
--- a/lib-prj
+++ b/lib-prj
@@ -1,9 +1,11 @@
 #!/bin/bash
 
 home() {
-	local me=`basename "$0"`
-	local utility_path=$(echo "`dirname \"$(which $me))\"`")
-	echo $utility_path # return value
+	#local me=`basename "$0"`
+	dirname ${BASH_SOURCE[0]}
+	#local me=`dirname ${BASH_SOURCE[0]}`
+	#local utility_path=$(echo "`dirname \"$(which $me))\"`")
+	#echo $utility_path # return value
 	}
 
 host () {
@@ -18,7 +20,26 @@ get_repos () {
 	 fi
 	echo "$repos" # return value
 	}
-
+find_prj () {
+	local path=$1
+	local prj=$2
+	[[ "$path" == "" ]] && echo "[LIB: FIND PROJECT] path for project is missed !" 1>&2 && return
+	[[ "$prj" == "" ]] && echo "[LIB: FIND PROJECT] project name is missed !" 1>&2 && return
+	#echo "path:$path"
+	#echo "prj:$prj"
+	(
+	cd $path
+	#pwd
+	#find . -type f ! -name "*.*" -maxdepth 1
+	for prj_loop in $(find . -type f ! -name "*.*" -maxdepth 1 | sed 's/^\.\///' ); do  #| tr -d '\r'
+		#echo "prj_loop: $prj_loop"
+		if [[ "$prj" == "$prj_loop" ]]; then
+			echo $prj_loop
+		  fi
+		#repo_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$repo_loop | tr -d '\r'`
+	  done
+	)
+  }
 # тильда в пути в переменной - крэшит параметр для команд (cd ls ..)
 	# eval - http://stackoverflow.com/questions/11065077/eval-command-in-bash-and-its-typical-uses 
 	# re="~(.*)"; if [[ $path =~ $re ]]; then  path=${BASH_REMATCH[1]}; fi; cd $HOME$path
diff --git a/pgo b/pgo
--- a/pgo
+++ b/pgo
@@ -1,24 +1,27 @@
 #!/bin/bash
+# . pgo <project> 
 # . pgo <repo> <in_list?>
 
-. lib-prj
+[ $SHLVL -gt 1 ] && echo "[GO TO PROJECT] Subshell can't change path after exit ! CORRECT USE: '. pgo <project>'" 1>&2 && exit
+#if expr match $parent $(which vim) > /dev/null
 
-# test 1st param - repo name
-p_repo="$1"
-[[ "$p_repo" == "" ]] && echo "[GO TO PROJECT] repo name is missed !"
+me=`dirname ${BASH_SOURCE[0]}` #echo "utility path: $me"
+. $me/lib-prj
 
-home=$(home) # echo home: $home
-host=$(host) # echo host: $host
-repos=$1; repos=$(get_repos $repos) # echo repos: $repos
+project="$1" # test 1st param - prj name
+[[ "$project" == "" ]] && echo "[GO TO PROJECT] project name is missed !"
 
-
-for repo_loop in $(cat $home/.cfg/$host/$repos.list | tr -d '\r'); do 
-	repo_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$repo_loop | tr -d '\r'`
-  done
-
+home=$(home) #; echo home: $home
+host=$(host) #; echo host: $host
+	# repos=$1; repos=$(get_repos $repos) # echo repos: $repos
+#echo path: "$home/.cfg/$host" 
+#find_prj "$home/.cfg/$host" $project
+prj_repo=$(find_prj "$home/.cfg/$host" $project) # echo prj_repo: $prj_repo
+[[ "$prj_repo" == "" ]] && echo "[GO TO PROJECT] project '$project' not found !" && return
 # extract path of repo
-repo_path="$(sed -E -n 's/^path=([^#]*)/\1/p' $home/.cfg/$host/$p_repo | tr -d '\r')" # echo repo_path: $repo_path
+project_path="$(sed -E -n 's/^path=([^#]*)/\1/p' $home/.cfg/$host/$prj_repo | tr -d '\r')" #; echo repo_path: $repo_path
 
-# go to prj
+echo "go to: $project_path"
 # ??TODO: test $path exists
-eval cd "$path"
+eval cd "$project_path"
+
