sk2-up

diff --git a/pren b/pren
--- a/pren
+++ b/pren
@@ -1,5 +1,6 @@
 #!/bin/bash
-# pren <prj> [<list>] 		# to curr_path
+# pren <prj> [<list>] 		# CASE #1 - rename prj name (find prj by curr_path)
+# pren <prj> [<list>] 		# CASE #2 - upd path of prj (find prj by name)
 # pren -n=<prj> -p=<path> -t=<type> -r=<remote> -s=<set>
 
 prj=$1
@@ -18,19 +19,29 @@ host=$(host) # echo host: $host
 if [[ "$list" == "" ]]; then
 	prj_list=$(get_repos).list 
   else
-  	prj_list=$list.list 
+  	prj_list="$list.list"
   fi
 # echo "prj_list: $prj_list"
 # TODO: test prj in list
 #exit
-	
-prj_file=$home/.cfg/$host/$prj
-[[ ! -f $prj_file ]] && echo "[PROJECT RENAME] Project is absent" && exit
 
-curr_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$prj | tr -d '\r'` ; echo curr_path: $curr_path
-echo "path=$new_path" 	>  $prj_file
-echo "type=git" 	>> $prj_file
-echo "remote=" 		>> $prj_file
+# CASE #1 - rename prj 
+curr_path=$(pwd)
+prj_name=$(find_prj_by_path "$home/.cfg/$host" $curr_path) #; echo prj_name: $prj_name	 #old prj name
+[[ $prj_name == "" ]] && echo "[PROJECT RENAME] Project file not found " && exit
+prj_file=$home/.cfg/$host/$prj_name
+#prj_path=`sed -E -n 's/^path=([^#]+).*/\1/p' $home/.cfg/$host/$prj | tr -d '\r'` #; echo curr_path: $prj_path
+mv "$prj_file" "$home/.cfg/$host/$prj" || exit
+#echo "list: $home/.cfg/$host/$prj_list"
+sed -i "s/^$prj_name\$/$prj/g" "$home/.cfg/$host/$prj_list" || exit # sed -i "s/^jr$/jrhw/g" `echo $home/.cfg/$host/$(get_repos).list`
+
+# TODO: CASE #2 - rename prj path
+#prj_file=$home/.cfg/$host/$prj
+#[[ ! -f $prj_file ]] && echo "[PROJECT RENAME] Project is absent" && exit
+
+#echo "path=$new_path" 	>  $prj_path
+#echo "type=git" 	>> $prj_file
+#echo "remote=" 		>> $prj_file
 
 plist
 
